### ISSUE TITLE
add mime type for AsciiDoc files

### ISSUE THREAD

**Issue by mojavelinux** [jshttp/mime-db#106]
Add the mime type `text/asciidoc` for AsciiDoc files. AsciiDoc files commonly end with `.adoc`, though the extensions `.asciidoc`, `.asc`, and sometimes `.ad` are also recognized. If we have to pick only one, it should be `.adoc`.

The mime type text/asciidoc follows the pattern used for Markdown, a very similar language. (see http://www.iana.org/assignments/media-types/text/markdown).

**Comment by dougwilson** [comment]
Yea, if there is a specification it can be manually added here with a link to the specification that states what the MIME is and file extenstions, etc. Ideally it is registered with the IANA (https://github.com/jshttp/mime-db/blob/master/README.md#adding-custom-media-types) which is our main source, but in the worse case it is not, it probably should be but we have a custom types area to get them listed early as long as there is a concrete specification to refer to.

**Comment by dougwilson** [comment]
Closing due to no movement for 3 months. You're still welcome to make a PR, but there is no clear indication for the timeline of closing the issue, so just trying to clean up. I know we had the conversation in #107 back all those months ago, but I haven't seen it pop up in the IANA registry, still. Ideally it is registered with the IANA (https://github.com/jshttp/mime-db/blob/master/README.md#adding-custom-media-types) which is our main source, but in the worse case it is not, it probably should be but we have a custom types area to get them listed early as long as there is a concrete specification to refer to.

**Comment by mojavelinux** [comment]
No worries. I know what I need to do. I just haven't gotten to it yet. I'll be back once I do it.
