### ISSUE TITLE
Add text/x-ssa

### ISSUE THREAD

**Issue by voxsoftware** [jshttp/mime-db#156]
Add text/x-ssa to database
https://reposcope.com/mimetype/text/x-ssa

**Comment by dougwilson** [comment]
Hello! If you can find a link to the primary source for that type (you link above is from another aggregation like this module), you can pull request it here following these instructions: https://github.com/jshttp/mime-db/blob/master/README.md#contributing

Otherwise, you'll want to instead get it registered with the IANA, which is a source we pull from. Instructions here: https://github.com/jshttp/mime-db/blob/master/README.md#adding-custom-media-types
