### ISSUE TITLE
".opus" extension for audio/opus

### ISSUE THREAD

**Issue by broofa** [jshttp/mime-db#193]
`audio/opus` type should map to `.opus` extension.

https://en.wikipedia.org/wiki/Opus_(audio_format)

**Comment by dougwilson** [comment]
If this mapping is not in one of our sources, it can be added here directly, but needs a source that lists both the file extension and mime type that is not another aggregation service or Wikipedia. The source for the file extension in that Wikipedia article is missing, so not sure where it came from in order to use that.

**Comment by broofa** [comment]
From https://tools.ietf.org/html/rfc7845#section-9:

> The RECOMMENDED filename extension for Ogg Opus files is '.opus'.

**Comment by dougwilson** [comment]
Yea, but isn't that for the mime `audio/ogg` ?

**Comment by broofa** [comment]
Ah, right.  This popped on my radar while updating node-mime unit tests to the latest list of types on MDN.  Not something I have the time/energy/interest to pursue however.  Sorry for the bother.
