### ISSUE TITLE
 Please add me as a member

### ISSUE THREAD

**Issue by alirealasad** [jshttp/mime-db#210]
thank you

**Comment by dougwilson** [comment]
Can you expand on the purpose? I'm not familiar with you.

**Comment by alirealasad** [comment]
I created Deno's version of [mime-db](https://github.com/alirealasad/mime_db) so I thought it belongs here and I also wanted to learn a thing or two.

**Comment by dougwilson** [comment]
Thank you. For former, I'm not sure what it means to belong here; if this module was not compatible with that system, it would make sense to be a separate repo, unless you want to articulate otherwise.

As for learning, adding you as a member is nothing more than you get fork just clicking to subscribe to the repo.

This repo is part of Express.js project and adding a member gives access to various resources around that, and we have an entire process for it. The main membership requirement is to actually make some sort of substantial contribution to the project, which I haven't seen here. You do not need to be a member to contribute to the project, both vs conversation or code.

**Comment by alirealasad** [comment]
I mean I actually wanted to create a separate repo for the project that's why I want to become a member but anyways sorry to waste your time.
