### ISSUE TITLE
Support for STEP and STP files

### ISSUE THREAD

**Issue by maxime1992** [jshttp/mime-db#222]
https://en.wikipedia.org/wiki/ISO_10303-21

I believe the content type should simply be `text/plain`

**Comment by dougwilson** [comment]
Hi @maxime1992 thanks for your issue. This module pulls from the three data sources listed at the top of the README; normally the method to get new MIME types added and/or extensions associated with a MIME type is for those sources to add it.

But otherwise, we provide two alternative methods:

1. https://github.com/jshttp/mime-db#adding-custom-media-types
2. https://github.com/jshttp/mime-db#contributing

I looked at those types are not listed in this module due to not appearing in our upstreams, so closing as this is not an issue somewhere in our pulling.
