### ISSUE TITLE
YAML is application/yaml

### ISSUE THREAD

**Issue by ioggstream** [jshttp/mime-db#274]
## I expect

- YAML media type registration is going to file application/yaml See https://datatracker.ietf.org/doc/draft-ietf-httpapi-yaml-mediatypes/

## Instead

- it is published as text/yaml

**Comment by dougwilson** [comment]
Hello, and thank you for providing that. It looks like that is still a draft, and so no guarantee that is going to be finalized. Once the registration is published, this module will pull it in automatically from IANA.

**Comment by ioggstream** [comment]
@dougwilson OK, thanks!

**Comment by dougwilson** [comment]
No problem! We have seen a few times over the years where some really ingrained type that was never registered had a draft RFC to change it to something else, but ultimately was abandoned due to friction to change it in reality. So we'll see if this actually gets published fully (and then it'll just be auto pulled in anyway by our feed to IANA).
