### ISSUE TITLE
Define .php files as text/html not application/x-httpd-php

### ISSUE THREAD

**Issue by ryandesign** [jshttp/mime-db#41]
GitHub Pages uses mime-db to decide what content type to use when serving static files. This means that a static file named "index.php" will be served with the MIME type "application/x-httpd-php" which makes the browser download the file instead of interpreting it. This makes it impossible for an existing web site, which happened to use PHP pages and ".php" extensions in its URLs, to migrate to GitHub Pages, without making all old links non-functional.

I suggest you change the MIME type for .php files to "text/html". This will make it possible for existing projects moving to GitHub Pages to preserve their existing URLs by creating static HTML files whose names match the old .php pages.

I initially reported this problem to GitHub Pages, and they directed me to file an issue here instead.

**Comment by dougwilson** [comment]
Hi @ryandesign! So this is a tricky one, because there is a difference between the PHP file itself (being `application/x-httpd-php`) and what the PHP file will actually output after being run (typically `text/html`). I don't think it makes sense to classify `.php` as `text/html` in this module, because this is a classification of the actual files themselves, but what they happen to output. Otherwise, `.asp`, `.pl`, and more would need to be changed to `text/html` in this module according to that logic.

If the question is about GitHub Pages, it's good to hear they are using this module to get their extension -> type mappings, but in reality, these are just _default mappings_. Ideally GitHub Pages should have a way for you to override the type of a given file extension and you could use that to set `.php` to map to `text/html` for your use-case.

**Comment by ryandesign** [comment]
> Ideally GitHub Pages should have a way for you to override the type of a given file extension and you could use that to set `.php` to map to `text/html` for your use-case.

I agree with you. I'll pass your recommendation on to them.

**Comment by dougwilson** [comment]
Haha, I went to see if this was possible, and it lead me to https://help.github.com/articles/mime-types-on-github-pages/ :) Seems like it may not be possible just yet, but may be valuable. We're happy to get anything added, for sure! This is just a weird one is all :) I understand what you are trying to do, which is to keep your linking working, which used to be `.php`, and I think that makes sense.
