### ISSUE TITLE
Should '.aac' map to 'audio/aac'?

### ISSUE THREAD

**Issue by broofa** [jshttp/mime-db#81]
```
> mimeTypes.lookup('aac')
'audio/x-aac'
```

`audio/aac` is a thing according to https://en.wikipedia.org/wiki/Advanced_Audio_Coding.  This is also what MDN says the type should at https://goo.gl/lHrFU6.

(Note: this isn't breaking anything for me... I just happened to notice this discrepancy while working up some new tests for node-mime)

**Comment by dougwilson** [comment]
So it looks like this extension + type map is coming from the Apache project (https://github.com/jshttp/mime-db/search?q=aac), though that doesn't mean we cannot also add a second definition for the plain audio/aac here, though it doesn't look like audio/aac is registered with the IANA, which is probably why it still has the x- prefix on it. I wish Wikipedia would actually show from what source those types on the sidebar came from, because since it's a wiki, anyone can just add it without any real reference to where it came from :(

**Comment by Martii** [comment]
@dougwilson 

W3 work for you at https://www.w3.org/2013/12/byte-stream-format-registry/mpeg-audio-byte-stream-format.html#h2_mime-types ?

**Comment by broofa** [comment]
Looks like it's official: https://www.iana.org/assignments/media-types/audio/aac

**Comment by ryanlin1986** [comment]
@dougwilson Any update on this? safari can not play with audio/x-aac
