### ISSUE TITLE
video/quicktime should map to .mov, not .qt

### ISSUE THREAD

**Issue by timcosta** [jshttp/mime-db#86]
Running into an issue where files with the extension `.mov` are getting the mimetype `video/qucktime`, and then if we decode the mimetype it comes back as `.qt`.

You can see that apache has updated their spec here: https://issues.apache.org/jira/browse/TIKA-1882

**Comment by dougwilson** [comment]
It is mapped to both in our database, as the type could be either or: https://github.com/jshttp/mime-db/blob/be37b05719ad488f4dcd5fd2c901f59608aeff1e/db.json#L6661-L6665

Apache also maps the type to both extensions in their mapping (http://svn.apache.org/repos/asf/httpd/httpd/trunk/docs/conf/mime.types):

> video/quicktime					qt mov

So what is the issue?

**Comment by timcosta** [comment]
@dougwilson I suppose my issue is likely in `node-mime` then, as it is returning `.qt` and not `.mov` for `video/quicktime`. Sorry about that, and thanks for the fast response!

**Comment by dougwilson** [comment]
Gotcha. I looked though out sources (we really just aggregate Apache + nginx + IANA) and it's just the Apache mappings that are providing the `.qt` extension mapping. If the Apache projects removes it, then it'll automatically get removed from this module, as the nature that we are just an aggregation. Our format is just a list of whatever extensions our sources have on file for a given type in an array.

I hope that helps / makes sense :) !

**Comment by aitchkhan** [comment]
Can we change the order and keep it like the following? Because the default for `video/quicktime` is `mov`. 
Even when I try to rename a file with `mov` to `qt` for saving a file from the internet. Mozilla Firefox asks me, do you really want to use `qt`? The standard is `mov`.

PS: I am not sure about the impact of this.

https://github.com/jshttp/mime-db/blob/be37b05719ad488f4dcd5fd2c901f59608aeff1e/db.json#L6661-L6665

```
  "video/quicktime": {
    "source": "apache",
    "compressible": false,
    "extensions": ["mov", "qt"]
  }
```

The packages dependent on mime-db returns the first element in the list, which in our case will return `qt`.

Screenshot of Mozilla Firefox:
<img width="858" alt="Screen Shot 2020-12-02 at 10 09 14 AM" src="https://user-images.githubusercontent.com/8606435/100830936-91b8c700-3486-11eb-9a52-f0931909cd1b.png">

**Comment by dougwilson** [comment]
> Can we change the order and keep it like the following?

The ordering come from the Apache project. You can ask them to change the ordering, ideally. Otherwise this project can override the ordering, but in order to do so, the normal requirements would need to ve met to add things here directly, namely some kind of primary source that states what you are saying. The web browser screenshot is not a primary source, unfortunately. The web browser would have gotten that information that one is standard vs the other from somewhere since web browsers are not Quicktime. Just need some kind of Quicmtime doc or Apple doc or something to override here.

**Comment by dougwilson** [comment]
I just looked at the logic for this module and adding extensions to the custom extensions doesn't overrule data coming from one of our sources, so overriding this data is not very straight forward. Ideally IANA would have at least `.mov` listed, but it has neither. This module aggregates in the order at the top of the README, so IANA -> Apache -> NGINX. Custom stuff is tacked on at the end. If Apache removed `.qt` (or changed the order) or IANA added `.mov` then it would actually end up in the suggested order in here by proxy.
